name: hotel_system_1
description: "A new Flutter project."
publish_to: 'none' # Remove this if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1  # ✅ Moved here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google.png
    - assets/facebook.png
    - assets/apple.png